name: publish apex-node-bundle
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to use for release'
        type: string
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
      - name: Update for Publishing
        run: |
          node scripts/updateForCoreBundle.js
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - name: Build the Project
        run: |
          yarn build
      - name: Publish a Package
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
