name: Test With Core Bunde
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to bundle core'
        type: string
        required: false
        default: main
      nodeVersion:
        description: version of node to use.  It's better to specify latest, lts/* or lts/-1 than to hardode numbers
        type: string
        required: false
        default: lts/*

jobs:
  build:
    name: Call build workflow
    uses: forcedotcom/bundle-publish-scripts/.github/workflows/build.yml@main
    with:
      branch: ${{ github.ref_name || inputs.branch }}
  tests:
    name: Call tests workflow
    uses: ./.github/workflows/testCommitExceptMain.yml

